server:
   port: 9999

eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
   instance:
      preferIpAddress: true
spring:
   cloud:
      stream:
         bindings:
            output:
               destination: productos
               contentType: text/plain

